name: ardilla
description: Stackivy Test Project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  url_launcher: ^6.1.7
  email_validator: ^2.1.17
  page_indicator_plus: ^1.0.3
  page_view_indicator_ns: ^1.0.0+1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: any

flutter_native_splash:
    background_image : assets/sp.png
    image : assets/logo.png

flutter:

  fonts:
    - family: Cabinet-Grotesk
      fonts:
        - asset: fonts/Cabinet-Grotesk-Bold.ttf
        - asset: fonts/Cabinet-Grotesk-Regular.ttf

  uses-material-design: true


  assets:
    - assets/box/1.png
    - assets/box/2.png
    - assets/box/3.png
    - assets/box/4.png
    - assets/icons/ic1.png
    - assets/icons/ic2.png
    - assets/icons/ic3.png
    - assets/icons/ic4.png
    - assets/icons/ic5.png
    - assets/icons/ic6.png
    - assets/icons/ic7.png
    - assets/icons/ic8.png
    - assets/cards/1.png
    - assets/cards/2.png
    - assets/cards/3.png
    - assets/cards/f1.png
    - assets/cards/f2.png
    - assets/cards/f3.png
    - assets/cards/f4.png
    - assets/cards/insure.png
    - assets/cards/invest.png
    - assets/cards/save.png
    - assets/nav/h1.png
    - assets/nav/h2.png
    - assets/nav/h3.png
    - assets/nav/h4.png
    - assets/nav/h5.png
    - assets/j.png
    - assets/ex.png
    - assets/ava.png
    - assets/top.png
    - assets/for.png
    - assets/logo.png
    - assets/fly.png
    - assets/graph.png
    - assets/wh_eye.png
    - assets/eye.png
    - assets/img.png
    - assets/onboard.png